using System.IO;
using System.Threading.Tasks;

using MediaDeck.Composition.Database;
using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Tables;
using MediaDeck.MediaItemTypes.Base.Models;

using Microsoft.Extensions.Logging;

namespace MediaDeck.MediaItemTypes.Pdf.Models;

[Inject(InjectServiceLifetime.Transient)]
public partial class PdfMediaItemOperator : BaseMediaItemOperator {
	private readonly IFilePathService _filePathService;
	private readonly ILogger<PdfMediaItemOperator> _logger;
	private readonly IPdfDocumentOperator _pdfDocumentOperator;

	public PdfMediaItemOperator(
		IFilePathService filePathService,
		ILogger<PdfMediaItemOperator> logger,
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService,
		IPdfDocumentOperator pdfDocumentOperator)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.Pdf) {
		this._filePathService = filePathService;
		this._logger = logger;
		this._pdfDocumentOperator = pdfDocumentOperator;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}

		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			var image = this._pdfDocumentOperator.CreateThumbnail(filePath, 300, 300, 1);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch (Exception ex) {
			this._logger.LogError(ex, "Failed to create pdf thumbnail for file {FilePath}", filePath);
			thumbPath = null;
			thumbRelativePath = null;
		}

		var pdfDocument = this._pdfDocumentOperator.GetPdfProperties(filePath);
		var fileInfo = new FileInfo(filePath);
		var directoryPath = Path.GetDirectoryName(filePath)!;
		var isUnderFolderGroup = await this.GetIsUnderFolderGroup(db, directoryPath);

		var mf = new MediaItem {
			MediaType = MediaType.Pdf,
			DirectoryPath = directoryPath,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			Width = (int)pdfDocument.Width,
			Height = (int)pdfDocument.Height,
			IsUnderFolderGroup = isUnderFolderGroup,
			Metadata = new() { Entries = [new() { Key = "PageCount", Value = pdfDocument.PageCount.ToString() }] }
		};

		await db.MediaItems.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaItemId);

		return mf;
	}

	public override async Task UpdateMetadata(MediaItem mediaItem) {
		using var fileMs = new MemoryStream();
		try {
			using var fileFs = File.OpenRead(mediaItem.FilePath);
			var pdfDocument = this._pdfDocumentOperator.GetPdfProperties(mediaItem.FilePath);

			mediaItem.Metadata = new() {
				Entries = [new() { Key = "PageCount", Value = pdfDocument.PageCount.ToString() }]
			};
		} catch (FileNotFoundException) {
			// TODO: notify
		}
	}
}