using System;
using System.Collections.Generic;

namespace PixChest.Utils.Tools;

public static class StringUtility {
	private static readonly int offset = beginKatakana - beginHiragana;
	private const char beginHiragana = 'ぁ';
	private const char endHiragana = 'ゖ';
	private const char beginKatakana = 'ァ';
	private const char endKatakana = 'ヶ';
	private static readonly Dictionary<string, string> char1 = new(){
		{"あ", "a"},
		{"い", "i"},
		{"う", "u"},
		{"え", "e"},
		{"お", "o"},
		{"ぁ", "xa"},
		{"ぃ", "xi"},
		{"ぅ", "xu"},
		{"ぇ", "xe"},
		{"ぉ", "xo"},
		{"か", "ka"},
		{"き", "ki"},
		{"く", "ku"},
		{"け", "ke"},
		{"こ", "ko"},
		{"が", "ga"},
		{"ぎ", "gi"},
		{"ぐ", "gu"},
		{"げ", "ge"},
		{"ご", "go"},
		{"さ", "sa"},
		{"し", "shi"},
		{"す", "su"},
		{"せ", "se"},
		{"そ", "so"},
		{"ざ", "za"},
		{"じ", "ji"},
		{"ず", "zu"},
		{"ぜ", "ze"},
		{"ぞ", "zo"},
		{"た", "ta"},
		{"ち", "chi"},
		{"つ", "tsu"},
		{"て", "te"},
		{"と", "to"},
		{"っ", "xtsu"},
		{"だ", "da"},
		{"ぢ", "di"},
		{"づ", "du"},
		{"で", "de"},
		{"ど", "do"},
		{"な", "na"},
		{"に", "ni"},
		{"ぬ", "nu"},
		{"ね", "ne"},
		{"の", "no"},
		{"は", "ha"},
		{"ひ", "hi"},
		{"ふ", "fu"},
		{"へ", "he"},
		{"ほ", "ho"},
		{"ば", "ba"},
		{"び", "bi"},
		{"ぶ", "bu"},
		{"べ", "be"},
		{"ぼ", "bo"},
		{"ぱ", "pa"},
		{"ぴ", "pi"},
		{"ぷ", "pu"},
		{"ぺ", "pe"},
		{"ぽ", "po"},
		{"ま", "ma"},
		{"み", "mi"},
		{"む", "mu"},
		{"め", "me"},
		{"も", "mo"},
		{"や", "ya"},
		{"ゆ", "yu"},
		{"よ", "yo"},
		{"ゃ", "xya"},
		{"ゅ", "xyu"},
		{"ょ", "xyo"},
		{"ら", "ra"},
		{"り", "ri"},
		{"る", "ru"},
		{"れ", "re"},
		{"ろ", "ro"},
		{"わ", "wa"},
		{"ゐ", "wi"},
		{"ゑ", "we"},
		{"を", "wo"},
		{"ゎ", "xwa"},
		{"ん", "n"},
		{"ー", "-"},
		{"、", ","},
		{"。", "."},
	};
	private static readonly Dictionary<string, string> char2 = new(){
		{"きゃ", "kya"},
		{"きぃ", "kyi"},
		{"きゅ", "kyu"},
		{"きぇ", "kye"},
		{"きょ", "kyo"},
		{"ぎゃ", "gya"},
		{"ぎぃ", "gyi"},
		{"ぎゅ", "gyu"},
		{"ぎぇ", "gye"},
		{"ぎょ", "gyo"},
		{"しゃ", "sha"},
		{"しぃ", "syi"},
		{"しゅ", "shu"},
		{"しぇ", "she"},
		{"しょ", "sho"},
		{"じゃ", "ja"},
		{"じぃ", "zyi"},
		{"じゅ", "ju"},
		{"じぇ", "je"},
		{"じょ", "jo"},
		{"ちゃ", "cha"},
		{"ちぃ", "tyi"},
		{"ちゅ", "chu"},
		{"ちぇ", "che"},
		{"ちょ", "cho"},
		{"ぢゃ", "dya"},
		{"ぢぃ", "dyi"},
		{"ぢゅ", "dyu"},
		{"ぢぇ", "dye"},
		{"ぢょ", "dyo"},
		{"てゃ", "tha"},
		{"てぃ", "thi"},
		{"てゅ", "thu"},
		{"てぇ", "the"},
		{"てょ", "tho"},
		{"にゃ", "nya"},
		{"にぃ", "nyi"},
		{"にゅ", "nyu"},
		{"にぇ", "nye"},
		{"にょ", "nyo"},
		{"ひゃ", "hya"},
		{"ひぃ", "hyi"},
		{"ひゅ", "hyu"},
		{"ひぇ", "hye"},
		{"ひょ", "hyo"},
		{"びゃ", "bya"},
		{"びぃ", "byi"},
		{"びゅ", "byu"},
		{"びぇ", "bye"},
		{"びょ", "byo"},
		{"ぴゃ", "pya"},
		{"ぴぃ", "pyi"},
		{"ぴゅ", "pyu"},
		{"ぴぇ", "pye"},
		{"ぴょ", "pyo"},
		{"みゃ", "mya"},
		{"みぃ", "myi"},
		{"みゅ", "myu"},
		{"みぇ", "mye"},
		{"みょ", "myo"},
		{"りゃ", "rya"},
		{"りぃ", "ryi"},
		{"りゅ", "ryu"},
		{"りぇ", "rye"},
		{"りょ", "ryo"},
		{"うぃ", "wi"},
		{"うぇ", "we"},
		{"くぁ", "kwa"},
		{"くぃ", "kwi"},
		{"くぅ", "kwu"},
		{"くぇ", "kwe"},
		{"くぉ", "kwo"},
		{"ぐぁ", "gwa"},
		{"ぐぃ", "gwi"},
		{"ぐぅ", "gwu"},
		{"ぐぇ", "gwe"},
		{"ぐぉ", "gwo"},
		{"とぁ", "twa"},
		{"とぃ", "twi"},
		{"とぅ", "twu"},
		{"とぇ", "twe"},
		{"とぉ", "two"},
		{"どぁ", "dwa"},
		{"どぃ", "dwi"},
		{"どぅ", "dwu"},
		{"どぇ", "dwe"},
		{"どぉ", "dwo"},
		{"ふぁ", "fa"},
		{"ふぃ", "fi"},
		{"ふぇ", "fe"},
		{"ふぉ", "fo"},
		{"っか", "kka"},
		{"っき", "kki"},
		{"っく", "kku"},
		{"っけ", "kke"},
		{"っこ", "kko"},
		{"っが", "gga"},
		{"っぎ", "ggi"},
		{"っぐ", "ggu"},
		{"っげ", "gge"},
		{"っご", "ggo"},
		{"っさ", "ssa"},
		{"っし", "sshi"},
		{"っす", "ssu"},
		{"っせ", "sse"},
		{"っそ", "sso"},
		{"っざ", "zza"},
		{"っじ", "jji"},
		{"っず", "zzu"},
		{"っぜ", "zze"},
		{"っぞ", "zzo"},
		{"った", "tta"},
		{"っち", "tchi"},
		{"っつ", "ttsu"},
		{"って", "tte"},
		{"っと", "tto"},
		{"っだ", "dda"},
		{"っぢ", "ddi"},
		{"っづ", "ddu"},
		{"っで", "dde"},
		{"っど", "ddo"},
		{"っは", "hha"},
		{"っひ", "hhi"},
		{"っふ", "ffu"},
		{"っへ", "hhe"},
		{"っほ", "hho"},
		{"っば", "bba"},
		{"っび", "bbi"},
		{"っぶ", "bbu"},
		{"っべ", "bbe"},
		{"っぼ", "bbo"},
		{"っぱ", "ppa"},
		{"っぴ", "ppi"},
		{"っぷ", "ppu"},
		{"っぺ", "ppe"},
		{"っぽ", "ppo"},
		{"っま", "mma"},
		{"っみ", "mmi"},
		{"っむ", "mmu"},
		{"っめ", "mme"},
		{"っも", "mmo"},
		{"っや", "yya"},
		{"っゆ", "yyu"},
		{"っよ", "yyo"},
		{"っら", "rra"},
		{"っり", "rri"},
		{"っる", "rru"},
		{"っれ", "rre"},
		{"っろ", "rro"},
		{"っわ", "wwa"},
		{"っゐ", "wwi"},
		{"っゑ", "wwe"},
		{"っを", "wwo"},
	};

	private static readonly Dictionary<string, string> char3 = new() {
		{"っきゃ", "kkya"},
		{"っきぃ", "kkyi"},
		{"っきゅ", "kkyu"},
		{"っきぇ", "kkye"},
		{"っきょ", "kkyo"},
		{"っぎゃ", "ggya"},
		{"っぎぃ", "ggyi"},
		{"っぎゅ", "ggyu"},
		{"っぎぇ", "ggye"},
		{"っぎょ", "ggyo"},
		{"っしゃ", "ssha"},
		{"っしぃ", "ssyi"},
		{"っしゅ", "sshu"},
		{"っしぇ", "sshe"},
		{"っしょ", "ssho"},
		{"っじゃ", "jja"},
		{"っじぃ", "jjyi"},
		{"っじゅ", "jju"},
		{"っじぇ", "jje"},
		{"っじょ", "jjo"},
		{"っちゃ", "tcha"},
		{"っちぃ", "ttyi"},
		{"っちゅ", "tchu"},
		{"っちぇ", "tche"},
		{"っちょ", "tcho"},
		{"っぢゃ", "ddya"},
		{"っぢぃ", "ddyi"},
		{"っぢゅ", "ddyu"},
		{"っぢぇ", "ddye"},
		{"っぢょ", "ddyo"},
		{"っひゃ", "hhya"},
		{"っひい", "hhyi"},
		{"っひゅ", "hhyu"},
		{"っひぇ", "hhye"},
		{"っひょ", "hhyo"},
		{"っびゃ", "bbya"},
		{"っびぃ", "bbyi"},
		{"っびゅ", "bbyu"},
		{"っびぇ", "bbye"},
		{"っびょ", "bbyo"},
		{"っぴゃ", "ppya"},
		{"っぴぃ", "ppyi"},
		{"っぴゅ", "ppyu"},
		{"っぴぇ", "ppye"},
		{"っぴょ", "ppyo"},
		{"っふぁ", "ffa"},
		{"っふぃ", "ffi"},
		{"っふぇ", "ffe"},
		{"っふぉ", "ffo"},
		{"っみゃ", "mmya"},
		{"っみぃ", "mmyi"},
		{"っみゅ", "mmyu"},
		{"っみぇ", "mmye"},
		{"っみょ", "mmyo"},
		{"っりゃ", "rrya"},
		{"っりぃ", "rryi"},
		{"っりゅ", "rryu"},
		{"っりぇ", "rrye"},
		{"っりょ", "rryo"}
	};


	public static string KatakanaToHiragana(this string text) {
		var result = "";
		foreach (var ch in text) {
			result += ch is >= beginKatakana and <= endKatakana ? (char)(ch - offset) : ch;
		}
		return result;
	}

	public static string HiraganaToRomaji(this string text) {
		var result = text;
		foreach (var c3 in char3) {
			result = result.Replace(c3.Key, c3.Value);
		}
		foreach (var c2 in char2) {
			result = result.Replace(c2.Key, c2.Value);
		}
		foreach (var c1 in char1) {
			result = result.Replace(c1.Key, c1.Value);
		}
		return result;
	}
}
