using System.Drawing;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

using FFMpegCore;

using MediaDeck.Composition.Database;
using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Interfaces.MediaItemTypes.Models;
using MediaDeck.Composition.Stores.Config.Model;
using MediaDeck.Composition.Tables;
using MediaDeck.Composition.Tables.Metadata;
using MediaDeck.MediaItemTypes.Base.Models;

using Microsoft.Extensions.Logging;

namespace MediaDeck.MediaItemTypes.Video.Models;

[Inject(InjectServiceLifetime.Transient)]
public partial class VideoMediaItemOperator : BaseMediaItemOperator {
	private readonly ConfigModel _config;
	private readonly IFilePathService _filePathService;
	private readonly ILogger<VideoMediaItemOperator> _logger;

	private static readonly string[] locationTagNames = [
		"TAG:location",
		"TAG:com.apple.quicktime.location.ISO6709"
	];

	public VideoMediaItemOperator(
		IFilePathService filePathService,
		ILogger<VideoMediaItemOperator> logger,
		ConfigModel config,
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.Video) {
		this._config = config;
		this._filePathService = filePathService;
		this._logger = logger;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}
		var metadata = FFProbe.Analyse(filePath);

		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			if (metadata.PrimaryVideoStream is not { } videoStream) {
				throw new Exception("PrimaryVideoStream is null");
			}
			var image = this.CreateThumbnail(filePath, videoStream.Width, videoStream.Height, 300, 300, metadata.Duration / 5);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch (Exception ex) {
			this._logger.LogError(ex, "Failed to create video thumbnail for file {FilePath}", filePath);
			thumbPath = null;
			thumbRelativePath = null;
		}

		var fileInfo = new FileInfo(filePath);
		var location = GetLocation(metadata);
		var directoryPath = Path.GetDirectoryName(filePath)!;
		var isUnderFolderGroup = await this.GetIsUnderFolderGroup(db, directoryPath);

		var mf = new MediaItem {
			MediaType = MediaType.Video,
			DirectoryPath = directoryPath,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			Latitude = location?.Latitude,
			Longitude = location?.Longitude,
			Altitude = location?.Altitude,
			Width = metadata.PrimaryVideoStream?.Width ?? 0,
			Height = metadata.PrimaryVideoStream?.Height ?? 0,
			IsUnderFolderGroup = isUnderFolderGroup,
			VideoFile = new() { Duration = metadata.PrimaryVideoStream?.Duration.TotalSeconds, Rotation = metadata.PrimaryVideoStream?.Rotation },
			Metadata = new() {
				Entries = metadata.PrimaryVideoStream?.Tags?.Select(x => new MediaMetadataEntry() { Key = x.Key, Value = x.Value }).ToList() ?? []
			}
		};

		await db.MediaItems.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaItemId);

		return mf;
	}

	public override async Task UpdateMetadata(MediaItem mediaItem) {
		using var fileMs = new MemoryStream();
		try {
			var metadata = FFProbe.Analyse(mediaItem.FilePath);

			mediaItem.Metadata = new() {
				Entries = metadata.PrimaryVideoStream?.Tags?.Select(x => new MediaMetadataEntry() { Key = x.Key, Value = x.Value }).ToList() ?? []
			};
		} catch (FileNotFoundException) {
			// TODO: notify
		}
	}

	/// <summary>
	/// サムネイル作成
	/// </summary>
	/// <param name="fileModel">動画ファイル</param>
	/// <param name="width">サムネイル幅</param>
	/// <param name="height">サムネイル高さ</param>
	/// <param name="time">時間指定</param>
	/// <returns>作成されたサムネイルファイル名</returns>
	public byte[] CreateThumbnail(IMediaItemModel fileModel, int width, int height, TimeSpan time) {
		var metadata = FFProbe.Analyse(fileModel.FilePath);
		if (metadata.PrimaryVideoStream is not { } videoStream) {
			throw new Exception("PrimaryVideoStream is null");
		}
		return this.CreateThumbnail(fileModel.FilePath, videoStream.Width, videoStream.Height, width, height, time);
	}

	/// <summary>
	/// サムネイル作成
	/// </summary>
	/// <param name="filePath">動画ファイルパス</param>
	/// <param name="originalWidth">元動画幅</param>
	/// <param name="originalHeight">元動画高さ</param>
	/// <param name="width">サムネイル幅</param>
	/// <param name="height">サムネイル高さ</param>
	/// <param name="time">時間指定</param>
	/// <returns>作成されたサムネイルファイル名</returns>
	public byte[] CreateThumbnail(string filePath, int originalWidth, int originalHeight, int width, int height, TimeSpan time) {
		if (originalWidth / width > originalHeight / height) {
			height = -1;
		} else {
			width = -1;
		}

		var uuid = Guid.NewGuid();
		var temporaryThumbPath = Path.Combine(this._config.PathConfig.TemporaryFolderPath.Value, $"{uuid}.png");
		FFMpeg.Snapshot(filePath, temporaryThumbPath, new Size(width, height), time);

		var binary = File.ReadAllBytes(temporaryThumbPath);
		File.Delete(temporaryThumbPath);
		return binary;
	}

	/// <summary>
	/// 位置情報取得
	/// </summary>
	/// <param name="mediaAnalysis">解析結果</param>
	/// <returns>位置情報</returns>
	private static (double Latitude, double Longitude, double? Altitude)? GetLocation(IMediaAnalysis mediaAnalysis) {
		var locationTag = mediaAnalysis.PrimaryVideoStream?.Tags?.FirstOrDefault(x => locationTagNames.Contains(x.Key)).Value;

		if (locationTag is null) {
			return null;
		}

		var match = LocationRegex().Match(locationTag);
		if (!match.Success) {
			return null;
		}
		var lat = match.Result("${lat}");
		var lon = match.Result("${lon}");
		var alt = match.Result("${alt}");

		if (alt != "") {
			return new(double.Parse(lat), double.Parse(lon), double.Parse(alt));
		} else {
			return new(double.Parse(lat), double.Parse(lon), null);
		}
	}

	[GeneratedRegex(@"^(?<lat>[\+-]\d+\.\d+?)(?<lon>[\+-]\d+\.\d+?)(?<alt>[\+-]\d+\.\d+?)?/$")]
	private static partial Regex LocationRegex();
}