<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MediaDeck.MediaItemTypes</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" />
    <PackageReference Include="MetadataExtractor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\lib\AutoDiAttributes\AutoDiAttributes.Generator\AutoDiAttributes.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\lib\GenJsonConfig\GenJsonConfig.Generators\GenJsonConfig.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\MediaDeck.Common\MediaDeck.Common.csproj" />
    <ProjectReference Include="..\MediaDeck.Composition\MediaDeck.Composition.csproj" />
  </ItemGroup>
</Project>