using System.IO;
using System.Threading.Tasks;
using MediaDeck.Composition.Database;
using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Tables;
using MediaDeck.MediaItemTypes.Base.Models;

namespace MediaDeck.MediaItemTypes.FolderGroup.Models;

[Inject(InjectServiceLifetime.Transient)]
public partial class FolderGroupMediaItemOperator : BaseMediaItemOperator {
	private readonly IFilePathService _filePathService;

	public FolderGroupMediaItemOperator(
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService,
		IFilePathService filePathService)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.FolderGroup) {
		this._filePathService = filePathService;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();

		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}
		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);

		var firstItem = await db.MediaItems
			.Where(x => x.DirectoryPath == filePath || x.DirectoryPath.StartsWith(filePath + Path.DirectorySeparatorChar))
			.Where(x => x.ThumbnailFileName != null)
			.OrderBy(x => x.FilePath)
			.FirstOrDefaultAsync();

		if (firstItem != null && firstItem.ThumbnailFileName != null) {
			new FileInfo(thumbPath).Directory?.Create();
			File.Copy(this._filePathService.GetThumbnailAbsoluteFilePath(firstItem.ThumbnailFileName), thumbPath, true);
		}

		var directoryInfo = new DirectoryInfo(filePath);

		var directoryPath = directoryInfo.Parent?.FullName ?? filePath;
		var isUnderFolderGroup = await this.GetIsUnderFolderGroup(db, directoryPath);
		var mediaItem = new MediaItem {
			MediaType = MediaType.FolderGroup,
			DirectoryPath = directoryPath,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = false,
			FileSize = 0,
			CreationTime = directoryInfo.Exists ? directoryInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = directoryInfo.Exists ? directoryInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = directoryInfo.Exists ? directoryInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = directoryInfo.Exists,
			IsUnderFolderGroup = isUnderFolderGroup
		};

		await db.MediaItems.AddAsync(mediaItem);
		await db.SaveChangesAsync();

		await db.MediaItems.Where(x => x.DirectoryPath == filePath || x.DirectoryPath.StartsWith(filePath + Path.DirectorySeparatorChar))
			.ExecuteUpdateAsync(x => x.SetProperty(p => p.IsUnderFolderGroup, true));

		await transaction.CommitAsync();

		return mediaItem;
	}
}