// <auto-generated>
// This file was modified to include Name and IsDefault properties for multi-tool support.
// </auto-generated>

using MediaDeck.Composition.Enum;
using R3.JsonConfig.Attributes;

namespace MediaDeck.Composition.Interfaces.MediaItemTypes.Models;

/// <summary>
/// 実行設定オブジェクトのインターフェース。
/// 各メディアタイプはこのインターフェースを実装し、固有のプロパティを定義する。
/// </summary>
[GenerateR3JsonConfigDto]
public interface IExecutionProgramObjectModel {
    /// <summary>
    /// 対象のメディアタイプ
    /// </summary>
    public MediaType MediaType { get; set; }

    /// <summary>
    /// ツール表示名（空の場合はパスから自動生成）
    /// </summary>
    public ReactiveProperty<string> Name { get; }

    /// <summary>
    /// 既定ツールかどうか
    /// </summary>
    public ReactiveProperty<bool> IsDefault { get; }
}