// <auto-generated>
// ArgumentPlaceholderResolver utility – resolves placeholders in execution arguments.
// </auto-generated>

using System.IO;

namespace MediaDeck.Common.Utilities;

/// <summary>
/// Provides methods to replace placeholders in a command argument template with actual file information.
/// Supported placeholders:
///   {path}        – Full file path (quoted)
///   {dir}         – Parent directory of the file (quoted)
///   {name}        – File name with extension
///   {namenoext}   – File name without extension
///   {ext}         – File extension (including the dot)
/// </summary>
public static class ArgumentPlaceholderResolver {
    public static string Resolve(string template, string filePath) {
        if (string.IsNullOrWhiteSpace(template)) {
            // If no template is provided, just return the quoted path.
            return $"\"{filePath}\"";
        }

        var dir = Path.GetDirectoryName(filePath) ?? string.Empty;
        var name = Path.GetFileName(filePath);
        var nameNoExt = Path.GetFileNameWithoutExtension(filePath);
        var ext = Path.GetExtension(filePath);

        return template
            .Replace("{path}", $"\"{filePath}\"")
            .Replace("{dir}", $"\"{dir}\"")
            .Replace("{name}", name)
            .Replace("{namenoext}", nameNoExt)
            .Replace("{ext}", ext);
    }
}
