using System.IO;
using System.IO.Compression;
using System.Threading.Tasks;
using ImageMagick;
using MediaDeck.Composition.Database;
using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Interfaces.MediaItemTypes;
using MediaDeck.Composition.Tables;
using MediaDeck.MediaItemTypes.Base.Models;
using MediaDeck.MediaItemTypes.Image.Utils;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace MediaDeck.MediaItemTypes.Archive.Models;

[Inject(InjectServiceLifetime.Transient)]
public partial class ArchiveMediaItemOperator : BaseMediaItemOperator {
	private IMediaItemTypeService _mediaItemTypeService {
		get {
			return field ??= this._serviceProvider.GetRequiredService<IMediaItemTypeService>();
		}
	}
	private readonly IFilePathService _filePathService;
	private readonly ILogger<ArchiveMediaItemOperator> _logger;
	private readonly IServiceProvider _serviceProvider;

	public ArchiveMediaItemOperator(
		IFilePathService filePathService,
		ILogger<ArchiveMediaItemOperator> logger,
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService,
		IServiceProvider serviceProvider)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.Archive) {
		this._filePathService = filePathService;
		this._logger = logger;
		this._serviceProvider = serviceProvider;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}
		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);

		using var archiveFile = ZipFile.Open(filePath, ZipArchiveMode.Read);

		var first = archiveFile.Entries.FirstOrDefault(x => this._mediaItemTypeService.IsTargetPath(x.Name, MediaType.Image));
		try {
			if (first != null) {
				var image = this.CreateThumbnail(archiveFile, 300, 300, first.FullName);
				new FileInfo(thumbPath).Directory?.Create();
				File.WriteAllBytes(thumbPath, image);
			}
		} catch (Exception ex) {
			this._logger.LogError(ex, "Failed to create archive thumbnail for file {FilePath}", filePath);
			thumbPath = null;
			thumbRelativePath = null;
		}

		var fileInfo = new FileInfo(filePath);
		var directoryPath = Path.GetDirectoryName(filePath)!;
		var isUnderFolderGroup = await this.GetIsUnderFolderGroup(db, directoryPath);
		var mf = new MediaItem {
			MediaType = MediaType.Archive,
			DirectoryPath = directoryPath,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			IsUnderFolderGroup = isUnderFolderGroup,
			Metadata = new() { Entries = [new() { Key = "PageCount", Value = archiveFile.Entries.Count(x => this._mediaItemTypeService.IsTargetPath(x.Name, MediaType.Image)).ToString() }] }
		};

		if (first != null) {
			try {
				using var stream = first!.Open();
				using var ms = new MemoryStream();
				stream.CopyTo(ms);
				ms.Seek(0, SeekOrigin.Begin);
				using var meta = ImageMetadataFactory.Create(ms);
				mf.Width = meta.Width;
				mf.Height = meta.Height;
			} catch (Exception ex) {
				this._logger.LogError(ex, "Failed to get image metadata for archive entry {EntryName} in file {FilePath}", first.FullName, filePath);
				mf.Width = 0;
				mf.Height = 0;
			}
		}

		await db.MediaItems.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaItemId);

		return mf;
	}

	/// <summary>
	/// サムネイル作成
	/// </summary>
	/// <param name="archiveFile">ファイル</param>
	/// <param name="width">サムネイル幅</param>
	/// <param name="height">サムネイル高さ</param>
	/// <param name="fileName">サムネイルにするファイル名</param>
	/// <returns>作成されたサムネイルファイル</returns>
	public byte[] CreateThumbnail(ZipArchive archiveFile, uint width, uint height, string fileName) {
		using var ms = new MemoryStream();
		using var stream = archiveFile.Entries.FirstOrDefault(x => x.FullName == fileName)!.Open();
		using var mi = new MagickImage(stream);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}
}