using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Tables.Metadata;

namespace MediaDeck.Composition.Tables;

/// <summary>
/// メディアアイテムテーブル
/// </summary>
public class MediaItem {
	/// <summary>
	/// メディアアイテムID
	/// </summary>
	public long MediaItemId {
		get;
		set;
	}

	public required MediaType MediaType {
		get;
		set;
	}

	/// <summary>
	/// ディレクトリパス
	/// </summary>
	public required string DirectoryPath {
		get;
		set;
	}

	/// <summary>
	/// ファイル名
	/// </summary>
	public required string FilePath {
		get;
		set;
	}

	/// <summary>
	/// サムネイルファイル名
	/// </summary>
	public string? ThumbnailFileName {
		get;
		set;
	}

	/// <summary>
	/// 最後に作成したサムネイルサイズ
	/// </summary>
	public int ThumbnailSize {
		get;
		set;
	}

	/// <summary>
	/// 緯度
	/// </summary>
	public double? Latitude {
		get;
		set;
	}

	/// <summary>
	/// 経度
	/// </summary>
	public double? Longitude {
		get;
		set;
	}

	/// <summary>
	/// 高度
	/// </summary>
	public double? Altitude {
		get;
		set;
	}

	/// <summary>
	/// ファイルサイズ
	/// </summary>
	public long FileSize {
		get;
		set;
	}

	/// <summary>
	/// 評価
	/// </summary>
	public int Rate {
		get;
		set;
	}

	/// <summary>
	/// 使用回数
	/// </summary>
	public int UsageCount {
		get;
		set;
	}

	/// <summary>
	/// 説明
	/// </summary>
	public required string Description {
		get;
		set;
	}

	/// <summary>
	/// 解像度 幅
	/// </summary>
	public int Width {
		get;
		set;
	}

	/// <summary>
	/// 解像度 高さ
	/// </summary>
	public int Height {
		get;
		set;
	}

	/// <summary>
	/// ファイルハッシュ(先頭1MB)
	/// </summary>
	public string? PreHash {
		get;
		set;
	}

	/// <summary>
	/// PreHash更新日時
	/// </summary>
	public DateTime? PreHashUpdatedTime {
		get;
		set;
	}

	/// <summary>
	/// ファイルハッシュ(全体)
	/// </summary>
	public string? FullHash {
		get;
		set;
	}

	/// <summary>
	/// FullHash更新日時
	/// </summary>
	public DateTime? FullHashUpdatedTime {
		get;
		set;
	}

	/// <summary>
	/// 作成日時
	/// </summary>
	public DateTime CreationTime {
		get;
		set;
	}

	/// <summary>
	/// 編集日時
	/// </summary>
	public DateTime ModifiedTime {
		get;
		set;
	}

	/// <summary>
	/// 最終アクセス日時
	/// </summary>
	public DateTime LastAccessTime {
		get;
		set;
	}

	/// <summary>
	/// 登録日時
	/// </summary>
	public DateTime RegisteredTime {
		get;
		set;
	}

	/// <summary>
	/// ファイルが存在するか否か
	/// </summary>
	public bool IsExists {
		get;
		set;
	}

	/// <summary>
	/// 不正ファイルか否か
	/// </summary>
	public bool IsInvalid {
		get;
		set;
	}

	/// <summary>
	/// 自動生成サムネイルか否か
	/// </summary>
	public bool IsAutoGeneratedThumbnail {
		get;
		set;
	}

	/// <summary>
	/// フォルダグループ配下のファイルか
	/// </summary>
	public required bool IsUnderFolderGroup {
		get;
		set;
	}

	/// <summary>
	/// タグリスト
	/// </summary>
	public virtual ICollection<MediaItemTag> MediaItemTags {
		get {
			return field ?? throw new InvalidOperationException();
		}
		set;
	}

	/// <summary>
	/// 所属アルバムリスト
	/// </summary>
	public virtual ICollection<MediaItemAlbum> MediaItemAlbums {
		get {
			return field ?? throw new InvalidOperationException();
		}
		set;
	}

	/// <summary>
	/// 動画ファイル
	/// </summary>
	public virtual VideoFile? VideoFile {
		get;
		set;
	}

	/// <summary>
	/// 画像ファイル
	/// </summary>
	public virtual ImageFile? ImageFile {
		get;
		set;
	}

	/// <summary>
	/// 位置情報
	/// </summary>
	public virtual Position? Position {
		get;
		set;
	}

	/// <summary>
	/// メタデータ（JSONカラム）
	/// </summary>
	public MediaMetadata? Metadata {
		get;
		set;
	}

	/// <summary>
	/// 追加情報（JSONカラム）
	/// </summary>
	public MediaItemAdditionalInfo? AdditionalInfo {
		get;
		set;
	}
}