using System.IO;
using System.Threading.Tasks;

using ImageMagick;

using MediaDeck.Composition.Database;
using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Interfaces.MediaItemTypes.Models;
using MediaDeck.Composition.Tables;
using MediaDeck.MediaItemTypes.Base.Models;
using MediaDeck.MediaItemTypes.Image.Utils;

namespace MediaDeck.MediaItemTypes.Image.Models;

[Inject(InjectServiceLifetime.Transient)]
public class ImageMediaItemOperator : BaseMediaItemOperator {
	private readonly IFilePathService _filePathService;

	public ImageMediaItemOperator(
		IFilePathService filePathService,
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.Image) {
		this._filePathService = filePathService;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}
		using var fileMs = new MemoryStream();

		using (var fileFs = File.OpenRead(filePath)) {
			fileFs.CopyTo(fileMs);
			fileMs.Position = 0;
		}
		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			var image = this.CreateThumbnail(fileMs, 300, 300);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch {
			thumbPath = null;
			thumbRelativePath = null;
		}

		var fileInfo = new FileInfo(filePath);
		var directoryPath = Path.GetDirectoryName(filePath)!;
		var isUnderFolderGroup = await this.GetIsUnderFolderGroup(db, directoryPath);

		var mf = new MediaItem {
			MediaType = MediaType.Image,
			DirectoryPath = directoryPath,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			IsUnderFolderGroup = isUnderFolderGroup
		};

		// metadata
		fileMs.Position = 0;
		using var meta = ImageMetadataFactory.Create(fileMs);

		if (meta.Latitude != null && meta.Longitude != null && meta.LatitudeRef != null && meta.LongitudeRef != null) {
			var latitude = (meta.Latitude[0].ToDouble() + (meta.Latitude[1].ToDouble() / 60) + (meta.Latitude[2].ToDouble() / 3600)) * (meta.LatitudeRef == "S" ? -1 : 1);
			var longitude = (meta.Longitude[0].ToDouble() + (meta.Longitude[1].ToDouble() / 60) + (meta.Longitude[2].ToDouble() / 3600)) * (meta.LongitudeRef == "W" ? -1 : 1);
			mf.Altitude = meta.Altitude?.ToDouble() * (meta.AltitudeRef == 1 ? -1 : 1);
			mf.Latitude = latitude;
			mf.Longitude = longitude;
			if (!db.Positions.Any(x => x.Latitude == latitude && x.Longitude == longitude)) {
				db.Add(new Position() { Latitude = latitude, Longitude = longitude });
			}
		}

		mf.Height = meta.Height;
		mf.Width = meta.Width;
		mf.Metadata = meta.CreateMetadata();

		await db.MediaItems.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaItemId);

		return mf;
	}

	public override async Task UpdateMetadata(MediaItem mediaItem) {

		using var fileMs = new MemoryStream();

		try {
			using (var fileFs = File.OpenRead(mediaItem.FilePath)) {
				using var meta = ImageMetadataFactory.Create(fileFs);
				mediaItem.Metadata = meta.CreateMetadata();
			}
		} catch (FileNotFoundException) {
			// TODO: notify
		}
	}

	public byte[] CreateThumbnail(IMediaItemModel fileModel, uint width, uint height) {
		using var fileFs = File.OpenRead(fileModel.FilePath);
		using var ms = new MemoryStream();
		using var mi = new MagickImage(fileFs);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}

	public byte[] CreateThumbnail(Stream fileStream, uint width, uint height) {
		using var ms = new MemoryStream();
		using var mi = new MagickImage(fileStream);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}
}