<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- VS Code や Roslyn 言語サーバーでのプロジェクトロード時に、WindowsAppSDKSelfContained が有効な状態で Platform が未指定または AnyCPU だとエラーが発生するのを防ぐため、デフォルトのプラットフォームを x64 に設定する -->
    <Platform Condition=" '$(Platform)' == '' or '$(Platform)' == 'AnyCPU' ">x64</Platform>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MediaDeck</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishTrimmed>False</PublishTrimmed>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug-Unpackaged;Release-Unpackaged</Configurations>
    <Packaged>true</Packaged>
    <Packaged Condition="'$(Configuration)' == 'Debug-Unpackaged' Or '$(Configuration)' == 'Release-Unpackaged'">false</Packaged>
    <DefineConstants Condition="'$(Configuration)' == 'Debug-Unpackaged'">$(DefineConstants);DEBUG</DefineConstants>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <DisableWinUISdkGeneratedMain>true</DisableWinUISdkGeneratedMain>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Packaged)' != 'true'">
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <DefineConstants>$(DefineConstants);UNPACKAGED</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" />
    <PackageReference Include="CommunityToolkit.WinUI.Collections" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.TokenizingTextBox" />
    <PackageReference Include="CommunityToolkit.WinUI.Converters" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="ObservableCollections" />
    <PackageReference Include="ObservableCollections.R3" />
    <PackageReference Include="R3" />
    <PackageReference Include="R3Extensions.WinUI3" />
    <PackageReference Include="System.Interactive" />
    <PackageReference Include="XAML.MapControl.WinUI" />
    <PackageReference Include="System.Reactive" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\lib\AutoDiAttributes\AutoDiAttributes.Generator\AutoDiAttributes.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\MediaDeck.Composition\MediaDeck.Composition.csproj" />
    <ProjectReference Include="..\MediaDeck.MediaItemTypes.UI\MediaDeck.MediaItemTypes.UI.csproj" />
    <ProjectReference Include="..\MediaDeck.Store\MediaDeck.Store.csproj" />
    <ProjectReference Include="..\MediaDeck.ViewModels\MediaDeck.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\thumbnail_creation_failed.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avcodec-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avdevice-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avfilter-11.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avformat-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avutil-60.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\swresample-6.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\swscale-9.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Text.Json.Serialization.EnableSourceGenReflectionFallback" Value="true" />
  </ItemGroup>

  <!-- .NET 10 で System.Text.Json のリフレクションベースのシリアライゼーションがデフォルトで無効になったことにFFMpegCoreが対応するまでの暫定対応 -->
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault" Value="true" />
    <RuntimeHostConfigurationOption Include="System.Text.Json.Serialization.EnableSourceGenReflectionFallback" Value="true" />
  </ItemGroup>
  <PropertyGroup>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <!-- .NET 10 で System.Text.Json のリフレクションベースのシリアライゼーションがデフォルトで無効になったことにFFMpegCoreが対応するまでの暫定対応 ここまで -->
  
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug-Unpackaged'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Release'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Release-Unpackaged'">True</PublishReadyToRun>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>