using PixChest.Database.Tables;
using System.IO;
using PixChest.Models.Files.Metadata.Images;
using PixChest.Models.Files.Metadata.Images.Formats;
using ImageMagick;
using PixChest.Utils.Enums;
using PixChest.Models.Files.FileTypes.Base;

namespace PixChest.Models.Files.FileTypes.Image;
public class ImageFileOperator : BaseFileOperator {
    public override MediaType TargetMediaType {
		get;
	} = MediaType.Image;

	public override void RegisterFile(string filepath) {
		using var transaction = this._db.Database.BeginTransaction();
		var isExists = this._db.MediaFiles.Any(x => x.FilePath == filepath);
		if (isExists) {
			return;
		}
		using var fileMs = new MemoryStream();

		using (var fileFs = File.OpenRead(filepath)) {
			fileFs.CopyTo(fileMs);
			fileMs.Position = 0;
		}
		var thumbPath = FilePathUtility.GetThumbnailRelativeFilePath(filepath);
		try {
			var image = this.CreateThumbnail(fileMs, 300, 300);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch {
			thumbPath = null;
		}

		var fileInfo = new FileInfo(filepath);

		var mf = new MediaFile {
			DirectoryPath = Path.GetDirectoryName(filepath)!,
			FilePath = filepath,
			ThumbnailFileName = thumbPath,
			Rate = -1,
			Description = "",
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Length,
			CreationTime = fileInfo.CreationTime,
			ModifiedTime = fileInfo.LastWriteTime,
			LastAccessTime = fileInfo.LastAccessTime
		};

		// metadata
		fileMs.Position = 0;
		using var meta = ImageMetadataFactory.Create(fileMs);

		if (meta.Latitude != null && meta.Longitude != null && meta.LatitudeRef != null && meta.LongitudeRef != null) {
			var latitude = (meta.Latitude[0].ToDouble() + (meta.Latitude[1].ToDouble() / 60) + (meta.Latitude[2].ToDouble() / 3600)) * (meta.LatitudeRef == "S" ? -1 : 1);
			var longitude = (meta.Longitude[0].ToDouble() + (meta.Longitude[1].ToDouble() / 60) + (meta.Longitude[2].ToDouble() / 3600)) * (meta.LongitudeRef == "W" ? -1 : 1);
			mf.Altitude = meta.Altitude?.ToDouble() * (meta.AltitudeRef == 1 ? -1 : 1);
			mf.Latitude = latitude;
			mf.Longitude = longitude;
			if (!this._db.Positions.Any(x => x.Latitude == latitude && x.Longitude == longitude)) {
				this._db.Add(new Position() { Latitude = latitude, Longitude = longitude });
			}
		}

		mf.Height = meta.Height;
		mf.Width = meta.Width;

		if (meta is Jpeg jpeg) {
			mf.Jpeg = jpeg.CreateMetadataRecord();
		} else if (meta is Png png) {
			mf.Png = png.CreateMetadataRecord();
		} else if (meta is Bmp bmp) {
			mf.Bmp = bmp.CreateMetadataRecord();
		} else if (meta is Gif gif) {
			mf.Gif = gif.CreateMetadataRecord();
		} else if (meta is Heif heif) {
			mf.Heif = heif.CreateMetadataRecord();
		}

		this._db.MediaFiles.Add(mf);
		this._db.SaveChanges();
		transaction.Commit();
	}

	public byte[] CreateThumbnail(Stream fileStream, int width, int height) {
		using var ms = new MemoryStream();
		using var mi = new MagickImage(fileStream);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}
}
