name: Lint and Format

on: [push]

jobs:
  check-format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore -p:EnableWindowsTargeting=true

      - name: Verify C# Formatting
        run: dotnet format --verify-no-changes --no-restore